name: CI/CD - Build, Push and Deploy

on:
  push:
    branches:
      - master

jobs:


  # CI 
  
  build-and-push:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_DB:  ${{ secrets.POSTGRES_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd=pg_isready
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 22
        uses: actions/setup-java@v4
        with:
          java-version: '22'
          distribution: 'temurin'
          cache: maven

      - name: Build and test with Maven
        run: ./mvnw clean package
        env:
          SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5432/${{ secrets.POSTGRES_DB }}
          SPRING_DATASOURCE_USERNAME: ${{ secrets.POSTGRES_USER }}
          SPRING_DATASOURCE_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest .

      - name: Push Docker image
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/demo-app:latest


 
  # CD 
  
  deploy:
    needs: build-and-push
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Kubernetes cluster
        run: kubectl get nodes

      - name: Create Kubernetes secrets
        run: |
          kubectl create secret generic db-secret --namespace demo --from-literal=POSTGRES_DB="${{ secrets.POSTGRES_DB }}" --from-literal=POSTGRES_USER="${{ secrets.POSTGRES_USER }}" --from-literal=POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" --dry-run=client -o yaml | kubectl apply -f -
          
          kubectl create secret generic demo-app-secret --namespace demo --from-literal=SPRING_DATASOURCE_USERNAME="${{ secrets.POSTGRES_USER }}" --from-literal=SPRING_DATASOURCE_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" --dry-run=client -o yaml | kubectl apply -f -

      - name: Apply Kubernetes manifests
        run: kubectl apply -f k8s/ 

      - name: Restart application deployment
        run: kubectl rollout restart deployment/demo-app -n demo

      - name: Wait for deploymentgit 
        run: kubectl rollout status deployment/demo-app -n demo --timeout=300s

      - name: Verify Kubernetes resources
        run: kubectl get all -n demo
